export enum CodStatus {
  COLLECTED = 'COLLECTED',
  VERIFIED = 'VERIFIED',
  DISCREPANCY = 'DISCREPANCY',
  TRANSFERRED = 'TRANSFERRED',
  DISPUTED = 'DISPUTED',
}

export enum CodTransferStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  TRANSFERRED = 'TRANSFERRED',
  FAILED = 'FAILED',
}
