export enum ReturnStatus {
  REQUESTED = 'REQUESTED',
  APPROVED = 'APPROVED',
  LABEL_CREATED = 'LABEL_CREATED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED_TO_SENDER = 'DELIVERED_TO_SENDER',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}

export enum ReturnReason {
  MAX_ATTEMPTS_REACHED = 'MAX_ATTEMPTS_REACHED',
  RECIPIENT_REFUSED = 'RECIPIENT_REFUSED',
  SENDER_REQUESTED = 'SENDER_REQUESTED',
  DAMAGED = 'DAMAGED',
  WRONG_ITEM = 'WRONG_ITEM',
}
